### ISSUE TITLE
"More" button and associated menu in clipboard are not spoken

### ISSUE THREAD

**Issue by sukiletxe** [josephsl/wintenApps#67]
First, I apologise if I must direct this to code. Tell me to do so and I'll close this and open an issue there.

When I copy some text to the clipboard and I access it with Win+
V, a menu with the available text is displayed. With object navigation I can see that there is a more button. I can't activate this button, or if I can activate it I can't notice its results, in any way (tried mouse routing and activating the object itself with NVDA + Enter in laptop keyboard). I can do so with Narrator (using tab and enter), and I can see this menu contains items such as pin, delete, and delete all.

(I have pinned items by accidents in the past, that's why I was looking for this button in the first place)

**Comment by cary-rowen** [comment]
Hi @josephsl 

Is this really unsolvable?
Both JAWS2022 and Narrator work as expected.

**Comment by josephsl** [comment]
Hi, nope due to focus issues (at least for NVDA at this time) – risks outweigh the benefits (NVDA getting stuck after moving system focus to let it announce these controls, repeated focus announcements especially in emoji panel portion). Besides in Windows 10, emoji panel is treated as an overlay – focus issue is somewhat resolved in Windows 11 but it has its own issues, namely focus getting stuck when closing clipboard history. Also, Windows 10 is in maintenance mode, so I expect no changes to emoji panel and clipboard history on Windows 10 unless Windows 11 panel is backported and focus issues are not seen (both are highly unlikely now). Sorry.
